theme: minima
title: Nasri Anis Blog
description: "Email: nasrianis213@gmail.com"
future: true
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
github_username: "annisvvv"jekyll-seo-tag
baseurl: ""