theme: minima
title: Nasri Anis Blog
description: "Email: nasrianis213@gmail.com"
future: true
baseurl: "/NasriAnis.Blog.github.io"
url: "https://annisvvv.github.io"

github_username: "annisvvv"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
