theme: minima
title: Nasri Anis Blog
description: "Email: nasrianis213@gmail.com"
future: true
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
github_username: "annisvvv"jekyll-seo-tag
baseurl: "/NasriAnis.Blog.github.io" # Add the repo name here with a slash
url: "https://annisvvv.github.io"    # Your main github.io address